import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'

import '@/design-system/themes/globalStyles.css'
import '@/design-system/themes/variations.css'
import { NavBar } from '@/design-system/organisms/Header'
import Provider from './Provider'
import { options } from './api/auth/[...nextauth]/options'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recepies',
  description: 'Generated by Stephane-Gon',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <NavBar.Root>
            <NavBar.Links>
              <NavBar.Link text='ABOUT' link="/about"/>
              <NavBar.Point />
              <NavBar.Link text='RECEPIES' link="/recepies"/>
              <NavBar.Point />
            </NavBar.Links>
            <NavBar.Logo link='/' />
            <NavBar.Links>
              <NavBar.Point />
              <NavBar.Link text='ME' link="/me"/>
              <NavBar.Point />
              <NavBar.Auth isLogged={false} />
            </NavBar.Links>
          </NavBar.Root>
          {children}
        </Provider>
      </body>
    </html>
  )
}
