import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/design-system/themes/globalStyles.css'
import '@/design-system/themes/variations.css'
import { NavBar } from '@/design-system/organisms/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recepies',
  description: 'Generated by Stephane-Gon',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar.Root>
          <NavBar.Links>
            <NavBar.Link text='ABOUT' link="#"/>
            <NavBar.Point />
            <NavBar.Link text='RECEPIES' link="#"/>
            <NavBar.Point />
          </NavBar.Links>
          <NavBar.Logo />
          <NavBar.Links>
            <NavBar.Point />
            <NavBar.Link text='ME' link="#"/>
            <NavBar.Point />
            <NavBar.Link text='GALLERY' link="#"/>
          </NavBar.Links>
        </NavBar.Root>
        {children}
      </body>
    </html>
  )
}
